report:
    resource: "@ReportBundle/Controller/"
    type:     annotation
    prefix:   /

fleet:
    resource: "@FleetBundle/Controller/"
    type:     annotation
    prefix:   /

client:
    resource: "@ClientBundle/Controller/"
    type:     annotation
    prefix:   /

address:
    resource: "@AddressBundle/Controller/"
    type:     annotation
    prefix:   /

company:
    resource: "@CompanyBundle/Controller/"
    type:     annotation
    prefix:   /

#user:
#    resource: "@UserBundle/Controller/"
#    type:     annotation
#    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@UserBundle/Resources/config/routing.yml"
